// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1BpWfFXm0AHbnqwPq-sikTZ77lqu-6Lo',
    appId: '1:1023013249912:web:25c00382960f6d25de1e8d',
    messagingSenderId: '1023013249912',
    projectId: 'marisanapp-33310',
    authDomain: 'marisanapp-33310.firebaseapp.com',
    storageBucket: 'marisanapp-33310.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuDfyrgf1eo6DL_tyA4vBdoelyGQj-gVo',
    appId: '1:1023013249912:android:c3be90aea80d110ade1e8d',
    messagingSenderId: '1023013249912',
    projectId: 'marisanapp-33310',
    storageBucket: 'marisanapp-33310.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEnr5DcSCF9CWXN8OG8ZzTGNB1HnSmzhA',
    appId: '1:1023013249912:ios:66446c1b21fd7570de1e8d',
    messagingSenderId: '1023013249912',
    projectId: 'marisanapp-33310',
    storageBucket: 'marisanapp-33310.appspot.com',
    iosClientId: '1023013249912-lq1htstmtfnl4r9v2lh67rqlbbcpoiev.apps.googleusercontent.com',
    iosBundleId: 'com.example.marisanif21a',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEnr5DcSCF9CWXN8OG8ZzTGNB1HnSmzhA',
    appId: '1:1023013249912:ios:677ef01aea61b4c2de1e8d',
    messagingSenderId: '1023013249912',
    projectId: 'marisanapp-33310',
    storageBucket: 'marisanapp-33310.appspot.com',
    iosClientId: '1023013249912-85u0ajcvdgsgp4of2493512tc230aval.apps.googleusercontent.com',
    iosBundleId: 'com.example.marisanif21a.RunnerTests',
  );
}
